### ISSUE TITLE
TrackParticles Diagnostic Smilei 4-3

### ISSUE THREAD

**Issue by flavorenti** [SmileiPIC/Smilei#233]
Hello everyone,

I've been running Smilei simulations for a while on supercomputers but I'm now trying for the first time to use the TrackParticles diagnostic. Indeed I'm having some problems with the happi post-processing.

When I try to open the TrackParticleDisordered_eon.h5 file I encounter the following error:

```
[flavorenti@castor my_scripts]$ python3 Trackparticles.py 
['/beegfs/SCRATCH/flavorenti/simu3D_classic/run0', '/beegfs/SCRATCH/flavorenti/simu3D_classic/run1', '/beegfs/SCRATCH/flavorenti/simu3D_classic/run2', '/beegfs/SCRATCH/flavorenti/simu3D_classic/run3', '/beegfs/SCRATCH/flavorenti/simu3D_classic/run4', '/beegfs/SCRATCH/flavorenti/simu3D_classic/run5', '/beegfs/SCRATCH/flavorenti/simu3D_classic/run6', '/beegfs/SCRATCH/flavorenti/simu3D_classic/run7', '/beegfs/SCRATCH/flavorenti/simu3D_classic/run8', '/beegfs/SCRATCH/flavorenti/simu3D_classic/run9']
/beegfs/SCRATCH/flavorenti/simu3D_classic/run0
WARNING: 'show=False' was set earlier. Restart python if you want figures to appear.
Loaded simulation '/beegfs/SCRATCH/flavorenti/simu3D_classic/run0'
Scanning for Scalar diagnostics
WARNING: you do not have the *pint* package, so you cannot modify units.
       : The results will stay in code units.
Scanning for Field diagnostics
Scanning for Probe diagnostics
Scanning for ParticleBinning diagnostics
Scanning for Screen diagnostics
Scanning for Tracked particle diagnostics
times ['0000000000', '0000000652', '0000001304', '0000001956', '0000002608', '0000003260', '0000003912', '0000004564']
Ordering particles ... (this could take a while)
/trinity/shared/apps/170135/x86_64/intel-2019/intelpython3/lib/python3.6/site-packages/h5py/_hl/dataset.py:313: H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
  "Use dataset[()] instead.", H5pyDeprecationWarning)
Number of particles: 89793653
    Ordering @ timestep = 0
Error in the ordering of the tracked particles
Traceback (most recent call last):
  File "Trackparticles.py", line 120, in <module>
    main(tbegin,tend,run_path,output_path,'pz_trackeons')
  File "Trackparticles.py", line 92, in main
    Diag = S.TrackParticles("eon", timesteps = int(t), axes=["pz"],select="all(t>0, (x>16.5)*(x<17.5))")
  File "/beegfs/home/flavorenti/Smilei-4.3/scripts/../happi/_core.py", line 531, in __call__
    return TrackParticles.TrackParticles(self._simulation, *args, **kwargs)
  File "/beegfs/home/flavorenti/Smilei-4.3/scripts/../happi/_Diagnostics/Diagnostic.py", line 78, in __init__
    remaining_kwargs = self._init(*args, **kwargs)
  File "/beegfs/home/flavorenti/Smilei-4.3/scripts/../happi/_Diagnostics/TrackParticles.py", line 41, in _init
    self._orderFiles(disorderedfiles, orderedfile, chunksize)
  File "/beegfs/home/flavorenti/Smilei-4.3/scripts/../happi/_Diagnostics/TrackParticles.py", line 506, in _orderFiles
    f0[name][it, first_o:last_o] = data[k][:npart_o]
TypeError: slice indices must be integers or None or have an __index__ method
```

This error comes out if I use sort=True, or some "select" option, using sort=False no error is encountered and all goes smooth.

## Parameters
- Smilei version 4.3
- Computing resources
  - LICALLO mesocluster, Nice, France
  - C++ compiler g++ (GCC) 8.3.0
  - Python version 3.6.8

Thanks, Federico Lavorenti

**Comment by mccoys** [comment]
This is probably related to the version of python. Let me see

**Comment by mccoys** [comment]
Are you using the latest from github ? or plain v4.3 ? Or something in between ?

**Comment by flavorenti** [comment]
Latest version, downloaded from smilei website (from http://www.maisondelasimulation.fr/smilei/_downloads/Smilei.tar.gz)

**Comment by mccoys** [comment]
Ok

Nevermind, I found the bug. We should be releasing v4.4 today, and this will be included.

**Comment by flavorenti** [comment]
great-thanks!
