### ISSUE TITLE
Post-processing related issue

### ISSUE THREAD

**Issue by Sonuphd** [SmileiPIC/Smilei#341]
Dear Sir,

I am working plasma wakefield acceleration by relativistic species initialization. But during post-processing, I am facing difficulty. Please solve my problem. I am sending you my error.
```
(base) sonu@sonu-HP-15-Notebook-PC:~$ cd PWFA
(base) sonu@sonu-HP-15-Notebook-PC:~/PWFA$ ipython
Python 3.8.3 (default, Jul  2 2020, 16:21:59) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.16.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import happi                                                                                                                          

In [2]: S = happi.Open("/home/sonu/PWFA")                                                                                                     
Traceback (most recent call last):

  File "/home/sonu/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-2-0b5a00f61056>", line 1, in <module>
    S = happi.Open("/home/sonu/PWFA")

  File "/home/sonu/Smilei/happi/_core.py", line 634, in Open
    return SmileiSimulation(*args, **kwargs)

  File "/home/sonu/Smilei/happi/_core.py", line 684, in __init__
    self.reload()

  File "/home/sonu/Smilei/happi/_core.py", line 786, in reload
    self.namelist, ndim_fields, ndim_particles, cell_length, ncels, timestep, reference_angular_frequency_SI = self._openNamelist(path)

  File "/home/sonu/Smilei/happi/_core.py", line 708, in _openNamelist
    exec(open(path+self._os.sep+'smilei.py').read(), namespace) # execute the namelist into an empty namespace

  File "<string>", line 1381
    profile = alpha*n0*profile_x*profile_r
                                          ^
TabError: inconsistent use of tabs and spaces in indentation
```

**Comment by mccoys** [comment]
there is a bug in your namelist. Look at the error
