### ISSUE TITLE
ERROR:root:Internal Python error in the inspect module.

### ISSUE THREAD

**Issue by Sanjeev273** [SmileiPIC/Smilei#343]
Hi smilei team members,

I have the following issue in Track-particles diagnostics when plotting the data but Particle ordering finish successfully.  
![error](https://user-images.githubusercontent.com/67734147/101846433-eb03b300-3b76-11eb-83ae-af936c876631.JPG)
![error2](https://user-images.githubusercontent.com/67734147/101846438-ed660d00-3b76-11eb-9340-1e151a8488d4.JPG)

Here is the output data file for simulation.
[activebeamdumping.sge.o1565740.txt](https://github.com/SmileiPIC/Smilei/files/5676389/activebeamdumping.sge.o1565740.txt)

**Comment by Sanjeev273** [comment]
The detailed error is as follows: 

In [7]: track.plot()
Loading data ...
   axis: x
   axis: px
Process broken lines ...
... done
Track particles: species 'electronbunch' containing 5400 particles
ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

Traceback (most recent call last):
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-3be19efd5565>", line 1, in <module>
  File "/opt/apps/apps/intel-18.0/smilei/4.5/happi/_Diagnostics/Diagnostic.py", line 283, in plot
    self._plotOnAxes(ax, timestep)
  File "/opt/apps/apps/intel-18.0/smilei/4.5/happi/_Diagnostics/TrackParticles.py", line 739, in _animateOnAxes_2D
    ax.plot(self._xfactor*x, self._yfactor*y, **self.options.plot)
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/matplotlib/axes/_axes.py", line 1649, in plot
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 1850, in add_line
    self._update_line_limits(line)
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 1872, in _update_line_limits
    path = line.get_path()
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/matplotlib/lines.py", line 1027, in get_path
    self.recache()
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/matplotlib/lines.py", line 679, in recache
    self._xy = np.column_stack(np.broadcast_arrays(x, y)).astype(float)
  File "<__array_function__ internals>", line 5, in column_stack
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/numpy/lib/shape_base.py", line 656, in column_stack
    return _nx.concatenate(arrays, 1)
  File "<__array_function__ internals>", line 5, in concatenate
MemoryError: Unable to allocate 348. KiB for an array with shape (22297, 2) and data type float64

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2044, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'MemoryError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1169, in get_records
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/ultratb.py", line 316, in wrapped
    return f(*args, **kwargs)
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/ultratb.py", line 350, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/inspect.py", line 1503, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/inspect.py", line 1461, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/inspect.py", line 708, in getsourcefile
    if getattr(getmodule(object, filename), '__loader__', None) is not None:
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/inspect.py", line 750, in getmodule
    _filesbymodname[modname] = f
MemoryError
ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

Traceback (most recent call last):
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-3be19efd5565>", line 1, in <module>
    track.plot()
  File "/opt/apps/apps/intel-18.0/smilei/4.5/happi/_Diagnostics/Diagnostic.py", line 283, in plot
    self._plotOnAxes(ax, timestep)
  File "/opt/apps/apps/intel-18.0/smilei/4.5/happi/_Diagnostics/TrackParticles.py", line 739, in _animateOnAxes_2D
    ax.plot(self._xfactor*x, self._yfactor*y, **self.options.plot)
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/matplotlib/axes/_axes.py", line 1649, in plot
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 1850, in add_line
    self._update_line_limits(line)
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 1872, in _update_line_limits
    path = line.get_path()
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/matplotlib/lines.py", line 1027, in get_path
    self.recache()
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/matplotlib/lines.py", line 679, in recache
    self._xy = np.column_stack(np.broadcast_arrays(x, y)).astype(float)
  File "<__array_function__ internals>", line 5, in column_stack
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/numpy/lib/shape_base.py", line 656, in column_stack
    return _nx.concatenate(arrays, 1)
  File "<__array_function__ internals>", line 5, in concatenate
MemoryError: Unable to allocate 348. KiB for an array with shape (22297, 2) and data type float64

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2044, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'MemoryError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3263, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3360, in run_code
    self.showtraceback(running_compiled_code=True)
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2046, in showtraceback
    stb = self.InteractiveTB.structured_traceback(etype,
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1435, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1335, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1192, in structured_traceback
    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1150, in format_exception_as_a_whole
    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/ultratb.py", line 451, in find_recursion
    return len(records), 0
TypeError: object of type 'NoneType' has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2044, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'TypeError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1169, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/ultratb.py", line 316, in wrapped
    return f(*args, **kwargs)
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/ultratb.py", line 350, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/inspect.py", line 1503, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/inspect.py", line 1461, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/inspect.py", line 708, in getsourcefile
    if getattr(getmodule(object, filename), '__loader__', None) is not None:
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/inspect.py", line 753, in getmodule
    modulesbyfile[f] = modulesbyfile[
MemoryError
ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

Traceback (most recent call last):
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-3be19efd5565>", line 1, in <module>
    track.plot()
  File "/opt/apps/apps/intel-18.0/smilei/4.5/happi/_Diagnostics/Diagnostic.py", line 283, in plot
    self._plotOnAxes(ax, timestep)
  File "/opt/apps/apps/intel-18.0/smilei/4.5/happi/_Diagnostics/TrackParticles.py", line 739, in _animateOnAxes_2D
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/matplotlib/axes/_axes.py", line 1649, in plot
    self.add_line(line)
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 1850, in add_line
    self._update_line_limits(line)
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 1872, in _update_line_limits
    path = line.get_path()
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/matplotlib/lines.py", line 1027, in get_path
    self.recache()
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/matplotlib/lines.py", line 679, in recache
    self._xy = np.column_stack(np.broadcast_arrays(x, y)).astype(float)
  File "<__array_function__ internals>", line 5, in column_stack
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/numpy/lib/shape_base.py", line 656, in column_stack
    return _nx.concatenate(arrays, 1)
  File "<__array_function__ internals>", line 5, in concatenate
MemoryError: Unable to allocate 348. KiB for an array with shape (22297, 2) and data type float64

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2044, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'MemoryError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3263, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3360, in run_code
    self.showtraceback(running_compiled_code=True)
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2046, in showtraceback
    stb = self.InteractiveTB.structured_traceback(etype,
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1435, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1335, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1192, in structured_traceback
    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1150, in format_exception_as_a_whole
    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/ultratb.py", line 451, in find_recursion
    return len(records), 0
TypeError: object of type 'NoneType' has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2044, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'TypeError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2895, in _run_cell
    return runner(coro)
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3071, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3282, in run_ast_nodes
    self.showtraceback()
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2046, in showtraceback
    stb = self.InteractiveTB.structured_traceback(etype,
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1435, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1335, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1210, in structured_traceback
    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1150, in format_exception_as_a_whole
    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/ultratb.py", line 451, in find_recursion
    return len(records), 0
TypeError: object of type 'NoneType' has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2044, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'TypeError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1169, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/ultratb.py", line 316, in wrapped
    return f(*args, **kwargs)
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/ultratb.py", line 350, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/inspect.py", line 1503, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/inspect.py", line 1461, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/inspect.py", line 708, in getsourcefile
    if getattr(getmodule(object, filename), '__loader__', None) is not None:
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/inspect.py", line 753, in getmodule
    modulesbyfile[f] = modulesbyfile[
MemoryError
Traceback (most recent call last):
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-3be19efd5565>", line 1, in <module>
  File "/opt/apps/apps/intel-18.0/smilei/4.5/happi/_Diagnostics/Diagnostic.py", line 283, in plot
    self._plotOnAxes(ax, timestep)
  File "/opt/apps/apps/intel-18.0/smilei/4.5/happi/_Diagnostics/TrackParticles.py", line 739, in _animateOnAxes_2D
    ax.plot(self._xfactor*x, self._yfactor*y, **self.options.plot)
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/matplotlib/axes/_axes.py", line 1649, in plot
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 1850, in add_line
    self._update_line_limits(line)
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 1872, in _update_line_limits
    path = line.get_path()
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/matplotlib/lines.py", line 1027, in get_path
    self.recache()
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/matplotlib/lines.py", line 679, in recache
    self._xy = np.column_stack(np.broadcast_arrays(x, y)).astype(float)
  File "<__array_function__ internals>", line 5, in column_stack
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/numpy/lib/shape_base.py", line 656, in column_stack
    return _nx.concatenate(arrays, 1)
  File "<__array_function__ internals>", line 5, in concatenate
MemoryError: Unable to allocate 348. KiB for an array with shape (22297, 2) and data type float64

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2044, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'MemoryError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3263, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3360, in run_code
    self.showtraceback(running_compiled_code=True)
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2046, in showtraceback
    stb = self.InteractiveTB.structured_traceback(etype,
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1435, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1335, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1192, in structured_traceback
    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1150, in format_exception_as_a_whole
    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/ultratb.py", line 451, in find_recursion
    return len(records), 0
TypeError: object of type 'NoneType' has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2044, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'TypeError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2895, in _run_cell
    return runner(coro)
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3071, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3282, in run_ast_nodes
    self.showtraceback()
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2046, in showtraceback
    stb = self.InteractiveTB.structured_traceback(etype,
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1435, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1335, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1210, in structured_traceback
    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1150, in format_exception_as_a_whole
    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/ultratb.py", line 451, in find_recursion
    return len(records), 0
TypeError: object of type 'NoneType' has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2044, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'TypeError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/apps/apps/binapps/anaconda3/2020.07/bin/ipython", line 11, in <module>
    sys.exit(start_ipython())
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/__init__.py", line 126, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/terminal/ipapp.py", line 356, in start
    self.shell.mainloop()
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/terminal/interactiveshell.py", line 563, in mainloop
    self.interact()
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/terminal/interactiveshell.py", line 554, in interact
    self.run_cell(code, store_history=True)
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2866, in run_cell
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2900, in _run_cell
    self.showtraceback(running_compiled_code=True)
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2046, in showtraceback
    stb = self.InteractiveTB.structured_traceback(etype,
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1435, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1335, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1210, in structured_traceback
    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1150, in format_exception_as_a_whole
    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/site-packages/IPython/core/ultratb.py", line 451, in find_recursion
    return len(records), 0
TypeError: object of type 'NoneType' has no len()

If you suspect this is an IPython 7.16.1 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

**Comment by mccoys** [comment]
`MemoryError` means you are out of memory. This might have been triggered by the fact that particle ordering uses a lot of memory, although you don't seem to have a lot of particles. You might also have other programs running that take a lot of memory. Restart and try again.

**Comment by Sanjeev273** [comment]
> 
> 
> `MemoryError` means you are out of memory. This might have been triggered by the fact that particle ordering uses a lot of memory, although you don't seem to have a lot of particles. You might also have other programs running that take a lot of memory. Restart and try again.

Hi @mccoys, The error occurred after particle ordering when I use the command "track.plot()" to plot the ordered particle data.

**Comment by mccoys** [comment]
did you restart your computer and try again ?

**Comment by Sanjeev273** [comment]
> 
> 
> did you restart your computer and try again ?

Yes I restart my local PC but not remote system because I am accessing it remotely. don't have permission to restart.

**Comment by mccoys** [comment]
It is no use restarting your home computer ! The memory is missing on the remote computer obviously. In this case there is not much we can do for you. This other computer does not have enough available memory. It looks strange because you have very few particles. Have you at least restarted python ?

**Comment by Sanjeev273** [comment]
Yes I tried all the possibilities.

**Comment by mccoys** [comment]
Have you tried selecting less particles ? less timesteps ? It is possible that you are simply asking too much

**Comment by Sanjeev273** [comment]
I can reduce the no. of particle but I can't reduce the time-steps. I used the less time steps  as much as possible. Its long run simulation.

**Comment by mccoys** [comment]
not the actual number of timesteps of the simulation but the timesteps you plot
