### ISSUE TITLE
Error reported by AddressSanitizer

### ISSUE THREAD

**Issue by iplasma** [SmileiPIC/Smilei#571]
## Description

AddressSanitizer (https://github.com/google/sanitizers/wiki/AddressSanitizer) reports detected memory error.

e.g., for tst1d_00_em_propagation.py or tst2d_00_em_propagation.py
```
=================================================================
==246969==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x602000009bf8 at pc 0x00000082cfc9 bp 0x7ffc55ffd3b0 sp 0x7ffc55ffd3a8
READ of size 4 at 0x602000009bf8 thread T0
    #0 0x82cfc8 in DiagnosticScalar::compute(Patch*, int) /users/Smilei/src/Diagnostic/DiagnosticScalar.cpp:650:22
    #1 0x10aaced in VectorPatch::runAllDiags(Params&, SmileiMPI*, unsigned int, Timers&, SimWindow*) /users/Smilei/src/Patch/VectorPatch.cpp:1327:37
    #2 0x12f3097 in main /users/Smilei/src/Smilei.cpp:332:20
    #3 0x7f0f04b1e349 in __libc_start_main (/lib64/libc.so.6+0x24349)
    #4 0x669e09 in _start /home/abuild/rpmbuild/BUILD/glibc-2.26/csu/../sysdeps/x86_64/start.S:120

0x602000009bf8 is located 0 bytes to the right of 8-byte region [0x602000009bf0,0x602000009bf8)
allocated by thread T0 here:
    #0 0x71b8ed in operator new(unsigned long) /home/amd/JENKINS/workspace/AOCC_3_2_0/llvm-project/compiler-rt/lib/asan/asan_new_delete.cpp:95:3
    #1 0x76de91 in __gnu_cxx::new_allocator<unsigned int>::allocate(unsigned long, void const*) /usr/lib64/gcc/x86_64-suse-linux/7/../../../../include/c++/7/ext/new_allocator.h:111:27
    #2 0x76de91 in std::allocator_traits<std::allocator<unsigned int> >::allocate(std::allocator<unsigned int>&, unsigned long) /usr/lib64/gcc/x86_64-suse-linux/7/../../../../include/c++/7/bits/alloc_traits.h:436:20
    #3 0x76de91 in std::_Vector_base<unsigned int, std::allocator<unsigned int> >::_M_allocate(unsigned long) /usr/lib64/gcc/x86_64-suse-linux/7/../../../../include/c++/7/bits/stl_vector.h:172:20
    #4 0x76de91 in std::vector<unsigned int, std::allocator<unsigned int> >::_M_default_append(unsigned long) /usr/lib64/gcc/x86_64-suse-linux/7/../../../../include/c++/7/bits/vector.tcc:571:34

SUMMARY: AddressSanitizer: heap-buffer-overflow /users/Smilei/src/Diagnostic/DiagnosticScalar.cpp:650:22 in DiagnosticScalar::compute(Patch*, int)
Shadow bytes around the buggy address:
  0x0c047fff9320: fa fa 00 04 fa fa 00 04 fa fa 00 04 fa fa 00 04
  0x0c047fff9330: fa fa 00 04 fa fa 00 fa fa fa 00 fa fa fa 00 fa
  0x0c047fff9340: fa fa 00 fa fa fa 00 04 fa fa 04 fa fa fa 00 04
  0x0c047fff9350: fa fa 04 fa fa fa 00 04 fa fa 04 fa fa fa 04 fa
  0x0c047fff9360: fa fa fd fd fa fa fd fa fa fa 04 fa fa fa 04 fa
=>0x0c047fff9370: fa fa fd fa fa fa fd fd fa fa 04 fa fa fa 00[fa]
  0x0c047fff9380: fa fa 00 fa fa fa 00 fa fa fa 00 fa fa fa 00 fa
  0x0c047fff9390: fa fa 04 fa fa fa 04 fa fa fa fd fa fa fa fd fa
  0x0c047fff93a0: fa fa fd fa fa fa 00 fa fa fa 00 fa fa fa 00 fa
  0x0c047fff93b0: fa fa 04 fa fa fa 00 04 fa fa 00 04 fa fa 00 fa
  0x0c047fff93c0: fa fa 00 fa fa fa 00 fa fa fa 00 fa fa fa 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==246969==ABORTING
```

for tst3d_00_em_propagation.py
```
=================================================================
==247043==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60300000f92f at pc 0x000000684424 bp 0x7ffd93895470 sp 0x7ffd93894c30
READ of size 60 at 0x60300000f92f thread T0
    #0 0x684423 in memcpy /home/amd/JENKINS/workspace/AOCC_3_2_0/llvm-project/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:827:5
    #1 0x7f1a3cd976eb in H5A__write (/opt/cray/pe/lib64/libhdf5_parallel_aocc.so.200+0x11b6eb)
    #2 0x7f1a3d015ba9 in H5VL__native_attr_write (/opt/cray/pe/lib64/libhdf5_parallel_aocc.so.200+0x399ba9)
    #3 0x7f1a3d000337 in H5VL_attr_write (/opt/cray/pe/lib64/libhdf5_parallel_aocc.so.200+0x384337)
    #4 0x7f1a3cd8c6db in H5Awrite (/opt/cray/pe/lib64/libhdf5_parallel_aocc.so.200+0x1106db)
    #5 0xe90f2d in H5Write::attr(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, DividedString&) /users/Smilei/src/Tools/H5.h:272:9
    #6 0xe90f2d in OpenPMDparams::writeMeshesAttributes(H5Write&) /users/Smilei/src/Params/OpenPMDparams.cpp:161:14
    #7 0x787f6e in DiagnosticFields::run(SmileiMPI*, VectorPatch&, int, SimWindow*, Timers&) /users/Smilei/src/Diagnostic/DiagnosticFields.cpp:298:23
    #8 0x10ab1e0 in VectorPatch::runAllDiags(Params&, SmileiMPI*, unsigned int, Timers&, SimWindow*) /users/Smilei/src/Patch/VectorPatch.cpp:1348:32
    #9 0x12f3097 in main /users/Smilei/src/Smilei.cpp:332:20
    #10 0x7f1a3a72a349 in __libc_start_main (/lib64/libc.so.6+0x24349)
    #11 0x669e09 in _start /home/abuild/rpmbuild/BUILD/glibc-2.26/csu/../sysdeps/x86_64/start.S:120

0x60300000f92f is located 0 bytes to the right of 31-byte region [0x60300000f910,0x60300000f92f)
allocated by thread T0 here:
    #0 0x71b8ed in operator new(unsigned long) /home/amd/JENKINS/workspace/AOCC_3_2_0/llvm-project/compiler-rt/lib/asan/asan_new_delete.cpp:95:3
    #1 0x7f1a3b30910d in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_mutate(unsigned long, unsigned long, char const*, unsigned long) /ptmp/peint/build-cray-gcc-20210813.230140.804215673/cray-gcc/BUILD/snos_objdir/x86_64-suse-linux/libstdc++-v3/include/bits/basic_string.tcc:307:30

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/amd/JENKINS/workspace/AOCC_3_2_0/llvm-project/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:827:5 in memcpy
Shadow bytes around the buggy address:
  0x0c067fff9ed0: 00 fa fa fa 00 00 00 fa fa fa 00 00 00 fa fa fa
  0x0c067fff9ee0: 00 00 00 fa fa fa 00 00 00 fa fa fa 00 00 00 fa
  0x0c067fff9ef0: fa fa 00 00 00 fa fa fa 00 00 00 fa fa fa 00 00
  0x0c067fff9f00: 00 fa fa fa 00 00 00 fa fa fa 00 00 00 fa fa fa
  0x0c067fff9f10: 00 00 00 fa fa fa 00 00 00 fa fa fa fd fd fd fd
=>0x0c067fff9f20: fa fa 00 00 00[07]fa fa fd fd fd fa fa fa 00 00
  0x0c067fff9f30: 00 fa fa fa 00 00 00 fa fa fa 00 00 00 fa fa fa
  0x0c067fff9f40: 00 00 00 fa fa fa 00 00 00 fa fa fa fd fd fd fa
  0x0c067fff9f50: fa fa 00 00 04 fa fa fa fd fd fd fd fa fa fd fd
  0x0c067fff9f60: fd fd fa fa 00 00 00 fa fa fa fd fd fd fa fa fa
  0x0c067fff9f70: fd fd fd fa fa fa 00 00 00 fa fa fa 00 00 00 fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==247043==ABORTING
```

## Steps to reproduce the problem

Add "-fsanitize=address -g" to the compiler flag. Compile then run tst1d_00_em_propagation.py,  tst2d_00_em_propagation.py and tst3d_00_em_propagation.py in the benchmarks directory.

## Parameters

- Smilei version : 4.7-236-ge13892daa-master

**Comment by mccoys** [comment]
Thank you for the report. These will be fixed in an upcoming update.

**Comment by mccoys** [comment]
These are already fixed in the develop branch. It will be merged in the master branch soon.
